name: CI Pipeline

on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - name: Run pytest tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt update && sudo apt install -y cmake g++
      - name: Build C++ project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
